<?php

namespace App\Http\Livewire\CMS;

class SidebarComponent extends Component
{
    public function getSidebars()
    {
        return collect(
            [
                [
                    'category' => null,
                    'roles' => 'Super User|Development|Hrd|Purchasing|Marketing|Finance',
                    'permissions' => 'Calendar',
                    'name' => trans('index.calendar'),
                    'slug' => 'calendar',
                    'icon' => 'fas fa-calendar fa-fw',
                    'url' => route("{$this->subDomain}.calendar.index"),
                    'pages' => null,
                ], [
                    'category' => null,
                    'roles' => 'Super User|Development|Hrd|Purchasing|Marketing|Finance',
                    'permissions' => 'My Task',
                    'name' => trans('index.my_task'),
                    'slug' => 'my-task',
                    'icon' => 'fas fa-tasks fa-fw',
                    'url' => route("{$this->subDomain}.my-task.index"),
                    'pages' => null,
                ], [
                    'category' => null,
                    'roles' => 'Super User|Development|Hrd|Purchasing|Marketing|Finance',
                    'permissions' => 'My Assignment',
                    'name' => trans('index.my_assignment'),
                    'slug' => 'my-assignment',
                    'icon' => 'fas fa-square-check fa-fw',
                    'url' => route("{$this->subDomain}.my-assignment.index"),
                    'pages' => null,
                ], [
                    'category' => null,
                    'roles' => 'Super User|Development|Hrd|Purchasing|Marketing|Finance',
                    'permissions' => 'My Absent',
                    'name' => trans('index.my_absent'),
                    'slug' => 'my-absent',
                    'icon' => 'fas fa-check-to-slot fa-fw',
                    'url' => route("{$this->subDomain}.my-absent.index"),
                    'pages' => null,
                ], [
                    'category' => null,
                    'roles' => 'Super User|Development|Hrd|Purchasing|Marketing|Finance',
                    'permissions' => 'My Salary',
                    'name' => trans('index.my_salary'),
                    'slug' => 'my-salary',
                    'icon' => 'fas fa-hand-holding-usd fa-fw',
                    'url' => route("{$this->subDomain}.my-salary.index"),
                    'pages' => null,
                ], [
                    'category' => null,
                    'roles' => 'Super User|Board Of Directors',
                    'permissions' => 'Board Of Directors',
                    'name' => trans('index.report'),
                    'slug' => 'report',
                    'icon' => 'fas fa-file-lines fa-fw',
                    'url' => route("{$this->subDomain}.report.index"),
                    'pages' => [
                        [
                            'roles' => 'Super User|Board Of Directors',
                            'permissions' => 'Absent Report',
                            'name' => trans('index.absent_report'),
                            'slug' => 'absent-report',
                            'icon' => 'fas fa-file-circle-check fa-fw',
                            'url' => route("{$this->subDomain}.report.absent-report.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Board Of Directors',
                            'permissions' => 'Annual Report',
                            'name' => trans('index.annual_report'),
                            'slug' => 'annual-report',
                            'icon' => 'fas fa-file-signature fa-fw',
                            'url' => route("{$this->subDomain}.report.annual-report.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Board Of Directors',
                            'permissions' => 'Balance Sheet',
                            'name' => trans('index.balance_sheet'),
                            'slug' => 'balance-sheet',
                            'icon' => 'fas fa-file-invoice fa-fw',
                            'url' => route("{$this->subDomain}.report.balance-sheet.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Board Of Directors',
                            'permissions' => 'Income Statement',
                            'name' => trans('index.income_statement'),
                            'slug' => 'income-statement',
                            'icon' => 'fas fa-file-invoice-dollar fa-fw',
                            'url' => route("{$this->subDomain}.report.income-statement.index"),
                            'categories' => null,
                        ],
                    ],
                ], [
                    'category' => null,
                    'roles' => 'Super User|Development',
                    'permissions' => 'Development',
                    'name' => trans('index.development'),
                    'slug' => 'development',
                    'icon' => 'fas fa-tools fa-fw',
                    'url' => route("{$this->subDomain}.development.index"),
                    'pages' => [
                        [
                            'roles' => 'Super User|Development',
                            'permissions' => 'Portfolio',
                            'name' => trans('index.portfolio'),
                            'slug' => 'portfolio',
                            'icon' => 'fas fa-th-large fa-fw',
                            'url' => route("{$this->subDomain}.development.portfolio.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Development',
                                    'permissions' => 'Portfolio',
                                    'name' => trans('index.portfolio'),
                                    'slug' => 'portfolio',
                                    'icon' => 'fas fa-th-large fa-fw',
                                    'url' => route("{$this->subDomain}.development.portfolio.index"),
                                ], [
                                    'roles' => 'Super User|Development',
                                    'permissions' => 'Portfolio Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.development.portfolio.category.index"),
                                ], [
                                    'roles' => 'Super User|Development',
                                    'permissions' => 'Portfolio Like',
                                    'name' => trans('index.like'),
                                    'slug' => 'portfolio-like',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.development.portfolio.like.index"),
                                ], [
                                    'roles' => 'Super User|Development',
                                    'permissions' => 'Portfolio Dislike',
                                    'name' => trans('index.dislike'),
                                    'slug' => 'portfolio-dislike',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.development.portfolio.dislike.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Development',
                            'permissions' => 'Product',
                            'name' => trans('index.product'),
                            'slug' => 'product',
                            'icon' => 'fas fa-boxes fa-fw',
                            'url' => route("{$this->subDomain}.development.product.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Development',
                                    'permissions' => 'Product',
                                    'name' => trans('index.product'),
                                    'slug' => 'product',
                                    'icon' => 'fas fa-boxes fa-fw',
                                    'url' => route("{$this->subDomain}.development.product.index"),
                                ], [
                                    'roles' => 'Super User|Development',
                                    'permissions' => 'Product Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.development.product.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Development',
                            'permissions' => 'Template',
                            'name' => trans('index.template'),
                            'slug' => 'template',
                            'icon' => 'fas fa-cubes fa-fw',
                            'url' => route("{$this->subDomain}.development.template.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Development',
                                    'permissions' => 'Template',
                                    'name' => trans('index.template'),
                                    'slug' => 'template',
                                    'icon' => 'fas fa-cubes fa-fw',
                                    'url' => route("{$this->subDomain}.development.template.index"),
                                ], [
                                    'roles' => 'Super User|Development',
                                    'permissions' => 'Template Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.development.template.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Development',
                            'permissions' => 'Task',
                            'name' => trans('index.task'),
                            'slug' => 'task',
                            'icon' => 'fas fa-tasks fa-fw',
                            'url' => route("{$this->subDomain}.development.task.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Development',
                            'permissions' => 'Assignment',
                            'name' => trans('index.assignment'),
                            'slug' => 'assignment',
                            'icon' => 'fas fa-square-check fa-fw',
                            'url' => route("{$this->subDomain}.development.assignment.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Development',
                            'permissions' => 'Progress',
                            'name' => trans('index.progress'),
                            'slug' => 'progress',
                            'icon' => 'fas fa-bars-progress fa-fw',
                            'url' => route("{$this->subDomain}.development.progress.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Development',
                            'permissions' => 'Revision',
                            'name' => trans('index.revision'),
                            'slug' => 'revision',
                            'icon' => 'fas fa-file-circle-check fa-fw',
                            'url' => route("{$this->subDomain}.development.revision.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Development',
                            'permissions' => 'Framework',
                            'name' => trans('index.framework'),
                            'slug' => 'framework',
                            'icon' => 'fas fa-screwdriver-wrench fa-fw',
                            'url' => route("{$this->subDomain}.development.framework.index"),
                            'categories' => null,
                        ],
                    ],
                ], [
                    'category' => null,
                    'roles' => 'Super User|Hrd',
                    'permissions' => 'Hrd',
                    'name' => trans('index.hrd'),
                    'slug' => 'hrd',
                    'icon' => 'fas fa-user-tie fa-fw',
                    'url' => route("{$this->subDomain}.hrd.index"),
                    'pages' => [
                        [
                            'roles' => 'Super User|Hrd',
                            'permissions' => 'Absent',
                            'name' => trans('index.absent'),
                            'slug' => 'absent',
                            'icon' => 'fas fa-check-to-slot fa-fw',
                            'url' => route("{$this->subDomain}.hrd.absent.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Hrd',
                            'permissions' => 'Employee',
                            'name' => trans('index.employee'),
                            'slug' => 'employee',
                            'icon' => 'fas fa-users fa-fw',
                            'url' => route("{$this->subDomain}.hrd.employee.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Hrd',
                            'permissions' => 'Endorse',
                            'name' => trans('index.endorse'),
                            'slug' => 'endorse',
                            'icon' => 'fas fa-people-group fa-fw',
                            'url' => route("{$this->subDomain}.hrd.endorse.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Hrd',
                            'permissions' => 'Client',
                            'name' => trans('index.client'),
                            'slug' => 'client',
                            'icon' => 'fas fa-user-tie fa-fw',
                            'url' => route("{$this->subDomain}.hrd.client.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Hrd',
                            'permissions' => 'Agent',
                            'name' => trans('index.agent'),
                            'slug' => 'agent',
                            'icon' => 'fas fa-user-secret fa-fw',
                            'url' => route("{$this->subDomain}.hrd.agent.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Hrd',
                            'permissions' => 'Career',
                            'name' => trans('index.career'),
                            'slug' => 'career',
                            'icon' => 'fas fa-briefcase fa-fw',
                            'url' => route("{$this->subDomain}.hrd.career.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Hrd',
                            'permissions' => 'Register Influencer',
                            'name' => trans('index.register_influencer'),
                            'slug' => 'register-influencer',
                            'icon' => 'fas fa-pen fa-fw',
                            'url' => route("{$this->subDomain}.hrd.register-influencer.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Hrd',
                            'permissions' => 'Sponsor',
                            'name' => trans('index.sponsor'),
                            'slug' => 'sponsor',
                            'icon' => 'fas fa-people-line fa-fw',
                            'url' => route("{$this->subDomain}.hrd.sponsor.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Hrd',
                            'permissions' => 'Testimonial',
                            'name' => trans('index.testimonial'),
                            'slug' => 'testimonial',
                            'icon' => 'fas fa-comments fa-fw',
                            'url' => route("{$this->subDomain}.hrd.testimonial.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Hrd',
                            'permissions' => 'Procedure',
                            'name' => trans('index.procedure'),
                            'slug' => 'procedure',
                            'icon' => 'fas fa-rectangle-list fa-fw',
                            'url' => route("{$this->subDomain}.hrd.procedure.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Hrd',
                                    'permissions' => 'Procedure',
                                    'name' => trans('index.procedure'),
                                    'slug' => 'procedure',
                                    'icon' => 'fas fa-rectangle-list fa-fw',
                                    'url' => route("{$this->subDomain}.hrd.procedure.index"),
                                ], [
                                    'roles' => 'Super User|Hrd',
                                    'permissions' => 'Procedure Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.hrd.procedure.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Hrd',
                            'permissions' => 'Rule',
                            'name' => trans('index.rule'),
                            'slug' => 'rule',
                            'icon' => 'fas fa-gavel fa-fw',
                            'url' => route("{$this->subDomain}.hrd.rule.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Hrd',
                                    'permissions' => 'Rule',
                                    'name' => trans('index.rule'),
                                    'slug' => 'rule',
                                    'icon' => 'fas fa-gavel fa-fw',
                                    'url' => route("{$this->subDomain}.hrd.rule.index"),
                                ], [
                                    'roles' => 'Super User|Hrd',
                                    'permissions' => 'Rule Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.hrd.rule.category.index"),
                                ],
                            ],
                        ],
                    ],
                ], [
                    'category' => null,
                    'roles' => 'Super User|Purchasing',
                    'permissions' => 'Purchasing',
                    'name' => trans('index.purchasing'),
                    'slug' => 'purchasing',
                    'icon' => 'fas fa-cash-register fa-fw',
                    'url' => route("{$this->subDomain}.purchasing.index"),
                    'pages' => [
                        [
                            'roles' => 'Super User|Purchasing',
                            'permissions' => 'Buy Advertisement',
                            'name' => trans('index.buy_advertisement'),
                            'slug' => 'buy-advertisement',
                            'icon' => 'fas fa-bullhorn fa-fw',
                            'url' => route("{$this->subDomain}.purchasing.buy-advertisement.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Purchasing',
                            'permissions' => 'Advertisement Provider',
                            'name' => trans('index.advertisement_provider'),
                            'slug' => 'advertisement-provider',
                            'icon' => 'fas fa-tags fa-fw',
                            'url' => route("{$this->subDomain}.purchasing.advertisement-provider.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Purchasing',
                            'permissions' => 'Buy Domain Hosting',
                            'name' => trans('index.buy_domain_hosting'),
                            'slug' => 'buy-domain-hosting',
                            'icon' => 'fas fa-server fa-fw',
                            'url' => route("{$this->subDomain}.purchasing.buy-domain-hosting.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Purchasing',
                            'permissions' => 'Domain Hosting Provider',
                            'name' => trans('index.domain_hosting_provider'),
                            'slug' => 'domain-hosting-provider',
                            'icon' => 'fas fa-tags fa-fw',
                            'url' => route("{$this->subDomain}.purchasing.domain-hosting-provider.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Purchasing',
                            'permissions' => 'Buy Internet',
                            'name' => trans('index.buy_internet'),
                            'slug' => 'buy-internet',
                            'icon' => 'fas fa-wifi fa-fw',
                            'url' => route("{$this->subDomain}.purchasing.buy-internet.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Purchasing',
                            'permissions' => 'Internet Provider',
                            'name' => trans('index.internet_provider'),
                            'slug' => 'internet-provider',
                            'icon' => 'fas fa-tags fa-fw',
                            'url' => route("{$this->subDomain}.purchasing.internet-provider.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Purchasing',
                            'permissions' => 'Buy Phone Credit',
                            'name' => trans('index.buy_phone_credit'),
                            'slug' => 'buy-phone-credit',
                            'icon' => 'fas fa-coins fa-fw',
                            'url' => route("{$this->subDomain}.purchasing.buy-phone-credit.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Purchasing',
                            'permissions' => 'Phone Credit Provider',
                            'name' => trans('index.phone_credit_provider'),
                            'slug' => 'phone-credit-provider',
                            'icon' => 'fas fa-tags fa-fw',
                            'url' => route("{$this->subDomain}.purchasing.phone-credit-provider.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Purchasing',
                            'permissions' => 'Buy Item',
                            'name' => trans('index.buy_item'),
                            'slug' => 'buy-item',
                            'icon' => 'fas fa-box fa-fw',
                            'url' => route("{$this->subDomain}.purchasing.buy-item.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Purchasing',
                            'permissions' => 'Buy Endorse',
                            'name' => trans('index.buy_endorse'),
                            'slug' => 'buy-endorse',
                            'icon' => 'fas fa-comments-dollar fa-fw',
                            'url' => route("{$this->subDomain}.purchasing.buy-endorse.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Purchasing',
                            'permissions' => 'Buy PLN Token',
                            'name' => trans('index.buy_pln_token'),
                            'slug' => 'buy-pln-token',
                            'icon' => 'fas fa-plug-circle-bolt fa-fw',
                            'url' => route("{$this->subDomain}.purchasing.buy-pln-token.index"),
                            'categories' => null,
                        ],
                    ],
                ], [
                    'category' => null,
                    'roles' => 'Super User|Marketing',
                    'permissions' => 'Marketing',
                    'name' => trans('index.marketing'),
                    'slug' => 'marketing',
                    'icon' => 'fas fa-bullhorn fa-fw',
                    'url' => route("{$this->subDomain}.marketing.index"),
                    'pages' => [
                        [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'News',
                            'name' => trans('index.news'),
                            'slug' => 'news',
                            'icon' => 'fas fa-newspaper fa-fw',
                            'url' => route("{$this->subDomain}.marketing.news.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Marketing',
                                    'permissions' => 'News',
                                    'name' => trans('index.news'),
                                    'slug' => 'news',
                                    'icon' => 'fas fa-newspaper fa-fw',
                                    'url' => route("{$this->subDomain}.marketing.news.index"),
                                ], [
                                    'roles' => 'Super User|Marketing',
                                    'permissions' => 'News Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.marketing.news.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'Blog',
                            'name' => trans('index.blog'),
                            'slug' => 'blog',
                            'icon' => 'fas fa-note-sticky fa-fw',
                            'url' => route("{$this->subDomain}.marketing.blog.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Marketing',
                                    'permissions' => 'Blog',
                                    'name' => trans('index.blog'),
                                    'slug' => 'blog',
                                    'icon' => 'fas fa-note-sticky fa-fw',
                                    'url' => route("{$this->subDomain}.marketing.blog.index"),
                                ], [
                                    'roles' => 'Super User|Marketing',
                                    'permissions' => 'Blog Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.marketing.blog.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'Game',
                            'name' => trans('index.game'),
                            'slug' => 'game',
                            'icon' => 'fas fa-gamepad fa-fw',
                            'url' => route("{$this->subDomain}.marketing.game.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Marketing',
                                    'permissions' => 'Game',
                                    'name' => trans('index.game'),
                                    'slug' => 'game',
                                    'icon' => 'fas fa-gamepad fa-fw',
                                    'url' => route("{$this->subDomain}.marketing.game.index"),
                                ], [
                                    'roles' => 'Super User|Marketing',
                                    'permissions' => 'Game Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.marketing.game.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'Job',
                            'name' => trans('index.job'),
                            'slug' => 'job',
                            'icon' => 'fas fa-suitcase fa-fw',
                            'url' => route("{$this->subDomain}.marketing.job.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Marketing',
                                    'permissions' => 'Job',
                                    'name' => trans('index.job'),
                                    'slug' => 'job',
                                    'icon' => 'fas fa-suitcase fa-fw',
                                    'url' => route("{$this->subDomain}.marketing.job.index"),
                                ], [
                                    'roles' => 'Super User|Marketing',
                                    'permissions' => 'Job Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.marketing.job.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'Forum',
                            'name' => trans('index.forum'),
                            'slug' => 'forum',
                            'icon' => 'fas fa-comment-dots fa-fw',
                            'url' => route("{$this->subDomain}.marketing.forum.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Marketing',
                                    'permissions' => 'Forum',
                                    'name' => trans('index.forum'),
                                    'slug' => 'forum',
                                    'icon' => 'fas fa-comment-dots fa-fw',
                                    'url' => route("{$this->subDomain}.marketing.forum.index"),
                                ], [
                                    'roles' => 'Super User|Marketing',
                                    'permissions' => 'Forum Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.marketing.forum.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'Order',
                            'name' => trans('index.order'),
                            'slug' => 'order',
                            'icon' => 'fas fa-cart-shopping fa-fw',
                            'url' => route("{$this->subDomain}.marketing.order.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'Contact',
                            'name' => trans('index.contact'),
                            'slug' => 'contact',
                            'icon' => 'fas fa-phone fa-fw',
                            'url' => route("{$this->subDomain}.marketing.contact.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'Promotion',
                            'name' => trans('index.promotion'),
                            'slug' => 'promotion',
                            'icon' => 'fas fa-gift fa-fw',
                            'url' => route("{$this->subDomain}.marketing.promotion.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'Price List',
                            'name' => trans('index.price_list'),
                            'slug' => 'price-list',
                            'icon' => 'fas fa-list-ol fa-fw',
                            'url' => route("{$this->subDomain}.marketing.price-list.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'Newsletter',
                            'name' => trans('index.newsletter'),
                            'slug' => 'newsletter',
                            'icon' => 'fas fa-envelopes-bulk fa-fw',
                            'url' => route("{$this->subDomain}.marketing.newsletter.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'Platform',
                            'name' => trans('index.platform'),
                            'slug' => 'platform',
                            'icon' => 'fas fa-circle-check fa-fw',
                            'url' => route("{$this->subDomain}.marketing.platform.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Marketing',
                            'permissions' => 'Service',
                            'name' => trans('index.service'),
                            'slug' => 'service',
                            'icon' => 'fas fa-wrench fa-fw',
                            'url' => route("{$this->subDomain}.marketing.service.index"),
                            'categories' => null,
                        ],
                    ],
                ], [
                    'category' => null,
                    'roles' => 'Super User|Finance',
                    'permissions' => 'Bank',
                    'name' => trans('index.finance'),
                    'slug' => 'finance',
                    'icon' => 'fas fa-wallet fa-fw',
                    'url' => route("{$this->subDomain}.finance.index"),
                    'pages' => [
                        [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Invoice Index',
                            'name' => trans('index.invoice'),
                            'slug' => 'invoice',
                            'icon' => 'fas fa-file-invoice fa-fw',
                            'url' => route("{$this->subDomain}.finance.invoice.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Payment Index',
                            'name' => trans('index.payment'),
                            'slug' => 'payment',
                            'icon' => 'fas fa-credit-card fa-fw',
                            'url' => route("{$this->subDomain}.finance.payment.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Finance',
                                    'permissions' => 'Payment',
                                    'name' => trans('index.payment'),
                                    'slug' => 'payment',
                                    'icon' => 'fas fa-credit-card fa-fw',
                                    'url' => route("{$this->subDomain}.finance.payment.index"),
                                ], [
                                    'roles' => 'Super User|Finance',
                                    'permissions' => 'Payment Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.finance.payment.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Charge Index',
                            'name' => trans('index.charge'),
                            'slug' => 'charge',
                            'icon' => 'fas fa-money-check fa-fw',
                            'url' => route("{$this->subDomain}.finance.charge.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Google Adsense Index',
                            'name' => trans('index.google_adsense'),
                            'slug' => 'google-adsense',
                            'icon' => 'fas fa-money-bill-wave fa-fw',
                            'url' => route("{$this->subDomain}.finance.google-adsense.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Salary',
                            'name' => trans('index.salary'),
                            'slug' => 'salary',
                            'icon' => 'fas fa-hand-holding-usd fa-fw',
                            'url' => route("{$this->subDomain}.finance.salary.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Loyalty',
                            'name' => trans('index.loyalty'),
                            'slug' => 'loyalty',
                            'icon' => 'fas fa-money-bill fa-fw',
                            'url' => route("{$this->subDomain}.finance.loyalty.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Deposit',
                            'name' => trans('index.deposit'),
                            'slug' => 'deposit',
                            'icon' => 'fas fa-arrow-alt-circle-down fa-fw',
                            'url' => route("{$this->subDomain}.finance.deposit.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Finance',
                                    'permissions' => 'Deposit',
                                    'name' => trans('index.deposit'),
                                    'slug' => 'deposit',
                                    'icon' => 'fas fa-arrow-alt-circle-down fa-fw',
                                    'url' => route("{$this->subDomain}.finance.deposit.index"),
                                ], [
                                    'roles' => 'Super User|Finance',
                                    'permissions' => 'Deposit Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.finance.deposit.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Withdraw',
                            'name' => trans('index.withdraw'),
                            'slug' => 'withdraw',
                            'icon' => 'fas fa-arrow-alt-circle-up fa-fw',
                            'url' => route("{$this->subDomain}.finance.withdraw.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Finance',
                                    'permissions' => 'Withdraw',
                                    'name' => trans('index.withdraw'),
                                    'slug' => 'withdraw',
                                    'icon' => 'fas fa-arrow-alt-circle-up fa-fw',
                                    'url' => route("{$this->subDomain}.finance.withdraw.index"),
                                ], [
                                    'roles' => 'Super User|Finance',
                                    'permissions' => 'Withdraw Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.finance.withdraw.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Donation',
                            'name' => trans('index.donation'),
                            'slug' => 'donation',
                            'icon' => 'fas fa-donate fa-fw',
                            'url' => route("{$this->subDomain}.finance.donation.index"),
                            'categories' => [
                                [
                                    'roles' => 'Super User|Finance',
                                    'permissions' => 'Donation',
                                    'name' => trans('index.donation'),
                                    'slug' => 'donation',
                                    'icon' => 'fas fa-donate fa-fw',
                                    'url' => route("{$this->subDomain}.finance.donation.index"),
                                ], [
                                    'roles' => 'Super User|Finance',
                                    'permissions' => 'Donation Category',
                                    'name' => trans('index.category'),
                                    'slug' => 'category',
                                    'icon' => 'fas fa-tags fa-fw',
                                    'url' => route("{$this->subDomain}.finance.donation.category.index"),
                                ],
                            ],
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Bank Interest',
                            'name' => trans('index.bank_interest'),
                            'slug' => 'bank-interest',
                            'icon' => 'fas fa-piggy-bank fa-fw',
                            'url' => route("{$this->subDomain}.finance.bank-interest.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Administrative Cost',
                            'name' => trans('index.administrative_cost'),
                            'slug' => 'administrative-cost',
                            'icon' => 'fas fa-money-bill-1 fa-fw',
                            'url' => route("{$this->subDomain}.finance.administrative-cost.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Bank',
                            'name' => trans('index.bank'),
                            'slug' => 'bank',
                            'icon' => 'fas fa-bank fa-fw',
                            'url' => route("{$this->subDomain}.finance.bank.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Finance',
                            'permissions' => 'Bank BCA',
                            'name' => trans('index.bank_bca'),
                            'slug' => 'bank-bca',
                            'icon' => 'fas fa-building-flag fa-fw',
                            'url' => route("{$this->subDomain}.finance.bank-bca.index"),
                            'categories' => null,
                        ],
                    ],
                ], [
                    'category' => null,
                    'roles' => 'Super User|Other',
                    'permissions' => 'Other',
                    'name' => trans('index.other'),
                    'slug' => 'other',
                    'icon' => 'fas fa-database fa-fw',
                    'url' => route("{$this->subDomain}.other.index"),
                    'pages' => [
                        [
                            'roles' => 'Super User|Other',
                            'permissions' => 'History',
                            'name' => trans('index.history'),
                            'slug' => 'history',
                            'icon' => 'fas fa-scroll fa-fw',
                            'url' => route("{$this->subDomain}.other.history.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Other',
                            'permissions' => 'Documentation',
                            'name' => trans('index.documentation'),
                            'slug' => 'documentation',
                            'icon' => 'fas fa-photo-film fa-fw',
                            'url' => route("{$this->subDomain}.other.documentation.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Other',
                            'permissions' => 'Quote',
                            'name' => trans('index.quote'),
                            'slug' => 'quote',
                            'icon' => 'fas fa-quote-left fa-fw',
                            'url' => route("{$this->subDomain}.other.quote.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Other',
                            'permissions' => 'Notification',
                            'name' => trans('index.notification'),
                            'slug' => 'notification',
                            'icon' => 'fas fa-bell fa-fw',
                            'url' => route("{$this->subDomain}.other.notification.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User|Other',
                            'permissions' => 'Faq',
                            'name' => trans('index.faq'),
                            'slug' => 'faq',
                            'icon' => 'fas fa-question-circle fa-fw',
                            'url' => route("{$this->subDomain}.other.faq.index"),
                            'categories' => null,
                        ],
                    ],
                ], [
                    'category' => null,
                    'roles' => 'Super User',
                    'permissions' => 'Configuration',
                    'name' => trans('index.configuration'),
                    'slug' => 'configuration',
                    'icon' => 'fas fa-gears fa-fw',
                    'url' => route("{$this->subDomain}.configuration.index"),
                    'pages' => [
                        [
                            'roles' => 'Super User',
                            'permissions' => 'User',
                            'name' => trans('index.user'),
                            'slug' => 'user',
                            'icon' => 'fas fa-user fa-fw',
                            'url' => route("{$this->subDomain}.configuration.user.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User',
                            'permissions' => 'Activity',
                            'name' => trans('index.activity'),
                            'slug' => 'activity',
                            'icon' => 'fas fa-history fa-fw',
                            'url' => route("{$this->subDomain}.configuration.activity.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User',
                            'permissions' => 'Role',
                            'name' => trans('index.role'),
                            'slug' => 'role',
                            'icon' => 'fas fa-suitcase fa-fw',
                            'url' => route("{$this->subDomain}.configuration.role.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User',
                            'permissions' => 'Permission',
                            'name' => trans('index.permission'),
                            'slug' => 'permission',
                            'icon' => 'fas fa-key fa-fw',
                            'url' => route("{$this->subDomain}.configuration.permission.index"),
                            'categories' => null,
                        ], [
                            'roles' => 'Super User',
                            'permissions' => 'Setting',
                            'name' => trans('index.setting'),
                            'slug' => 'setting',
                            'icon' => 'fas fa-gear fa-fw',
                            'url' => route("{$this->subDomain}.configuration.setting.index"),
                            'categories' => null,
                        ],
                    ],
                ],
            ],
        );
    }

    public function render()
    {
        return view("{$this->subDomain}.livewire.layout.sidebar", [
            'sidebars' => $this->getSidebars(),
        ])->extends("{$this->subDomain}.layouts.app")->section('content');
    }
}
